/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ModEstoqueControl;
import entities.Fornecedor;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author erick.costa
 */
public class ModuloEstoque extends javax.swing.JPanel {
    
    ModEstoqueControl control;
    private static ModuloEstoque instancia;

    /**
     * Creates new form ModuloEstoque
     */
    private ModuloEstoque(TelaPrincipal framePrincipal, boolean modoFornecedor, Fornecedor fornecedor) {
        control = new ModEstoqueControl(framePrincipal, this, modoFornecedor, fornecedor);
        initComponents();
        control.modoFornecedor();
    }
    
    public static synchronized ModuloEstoque getInstancia(TelaPrincipal framePrincipal, boolean modoFornecedor, Fornecedor fornecedor) {
        if (instancia == null) {
            instancia = new ModuloEstoque(framePrincipal, modoFornecedor, fornecedor);
        }
        return instancia;
    }
    
    public static void reset() {
        instancia = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPrecoCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfIntervaloPrecoCompraInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfIntervaloPrecoCompraFim = new javax.swing.JTextField();
        btAplicar = new javax.swing.JButton();
        btZerar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfPrecoVenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfIntervaloPrecoVendaFim = new javax.swing.JTextField();
        tfIntervaloPrecoVendaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        btCadastrarProduto = new javax.swing.JButton();
        btExcluirProduto = new javax.swing.JButton();
        btAlterarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btComprasProduto = new javax.swing.JButton();
        btVendasProduto = new javax.swing.JButton();
        btGerarPdf = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Estoque");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jLabel2.setText("Nome do Produto");

        jLabel4.setText("Preço Compra");

        tfPrecoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPrecoCompraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrecoCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecoCompraKeyTyped(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Intervalo de Preço Venda");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Intervalo de Preço Compra");

        tfIntervaloPrecoCompraInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoCompraInicioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoCompraInicioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoCompraInicioKeyTyped(evt);
            }
        });

        jLabel8.setText("e");

        tfIntervaloPrecoCompraFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoCompraFimKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoCompraFimKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoCompraFimKeyTyped(evt);
            }
        });

        btAplicar.setText("Aplicar");
        btAplicar.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btAplicar.setPreferredSize(new java.awt.Dimension(39, 20));
        btAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAplicarMouseClicked(evt);
            }
        });

        btZerar.setText("Zerar");
        btZerar.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btZerar.setPreferredSize(new java.awt.Dimension(39, 20));
        btZerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btZerarMouseClicked(evt);
            }
        });

        jLabel6.setText("Preço Venda");

        tfPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPrecoVendaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrecoVendaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecoVendaKeyTyped(evt);
            }
        });

        jLabel9.setText("e");

        tfIntervaloPrecoVendaFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoVendaFimKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoVendaFimKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoVendaFimKeyTyped(evt);
            }
        });

        tfIntervaloPrecoVendaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoVendaInicioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoVendaInicioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIntervaloPrecoVendaInicioKeyTyped(evt);
            }
        });

        jLabel3.setText("Quantidade");

        tfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(tfPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(79, 79, 79))
                                    .addComponent(tfPrecoVenda)))
                            .addComponent(jLabel2)
                            .addComponent(tfProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfIntervaloPrecoCompraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfIntervaloPrecoCompraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfIntervaloPrecoVendaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfIntervaloPrecoVendaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addComponent(btAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btZerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIntervaloPrecoCompraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfIntervaloPrecoCompraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btZerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIntervaloPrecoVendaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tfIntervaloPrecoVendaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22)))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCadastrarProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btCadastrarProduto.setText("+");
        btCadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastrarProdutoMouseClicked(evt);
            }
        });

        btExcluirProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btExcluirProduto.setText("-");
        btExcluirProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirProdutoMouseClicked(evt);
            }
        });

        btAlterarProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btAlterarProduto.setText("*");
        btAlterarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarProdutoMouseClicked(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        btComprasProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btComprasProduto.setText("Ver Compras deste Produto");
        btComprasProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btComprasProdutoMouseClicked(evt);
            }
        });

        btVendasProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVendasProduto.setText("Ver Vendas deste Produto");
        btVendasProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVendasProdutoMouseClicked(evt);
            }
        });

        btGerarPdf.setText("Gerar PDF");
        btGerarPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGerarPdfMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Comprar Estoque");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btComprasProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVendasProduto)
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastrarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btGerarPdf)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btComprasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btVendasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btGerarPdf, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarProdutoMouseClicked
        control.cadastrarProdutoAction();
    }//GEN-LAST:event_btCadastrarProdutoMouseClicked

    private void btAlterarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarProdutoMouseClicked
        control.alterarProdutoAction();
    }//GEN-LAST:event_btAlterarProdutoMouseClicked

    private void btExcluirProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirProdutoMouseClicked
        control.excluirAction();
    }//GEN-LAST:event_btExcluirProdutoMouseClicked

    private void btComprasProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btComprasProdutoMouseClicked
        control.verCompraProdutoAction();
    }//GEN-LAST:event_btComprasProdutoMouseClicked

    private void btGerarPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerarPdfMouseClicked
        control.gerarPdf();
    }//GEN-LAST:event_btGerarPdfMouseClicked

    private void tfIntervaloPrecoCompraInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoCompraInicioKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfIntervaloPrecoCompraInicioKeyPressed

    private void tfIntervaloPrecoCompraInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoCompraInicioKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfIntervaloPrecoCompraInicio());
    }//GEN-LAST:event_tfIntervaloPrecoCompraInicioKeyTyped

    private void tfIntervaloPrecoCompraFimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoCompraFimKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfIntervaloPrecoCompraFimKeyPressed

    private void tfIntervaloPrecoCompraFimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoCompraFimKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfIntervaloPrecoCompraFim());
    }//GEN-LAST:event_tfIntervaloPrecoCompraFimKeyTyped

    private void tfQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfQuantidadeKeyPressed

    private void tfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfQuantidade());
    }//GEN-LAST:event_tfQuantidadeKeyTyped

    private void tfIntervaloPrecoVendaInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoVendaInicioKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfIntervaloPrecoVendaInicioKeyPressed

    private void tfIntervaloPrecoVendaInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoVendaInicioKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfIntervaloPrecoVendaInicio());
    }//GEN-LAST:event_tfIntervaloPrecoVendaInicioKeyTyped

    private void tfIntervaloPrecoVendaFimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoVendaFimKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfIntervaloPrecoVendaFimKeyPressed

    private void tfIntervaloPrecoVendaFimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoVendaFimKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfIntervaloPrecoVendaFim());
    }//GEN-LAST:event_tfIntervaloPrecoVendaFimKeyTyped

    private void tfPrecoCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoCompraKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfPrecoCompraKeyPressed

    private void tfPrecoCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoCompraKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfPrecoCompra());
    }//GEN-LAST:event_tfPrecoCompraKeyTyped

    private void tfPrecoVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoVendaKeyPressed
        control.salvaKeyCode(evt);
    }//GEN-LAST:event_tfPrecoVendaKeyPressed

    private void tfPrecoVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoVendaKeyTyped
        control.filtroCampoMonetario(evt);
        //control.validaCampoMonetario(getTfPrecoVenda());
    }//GEN-LAST:event_tfPrecoVendaKeyTyped

    private void tfIntervaloPrecoCompraInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoCompraInicioKeyReleased
        control.validaCampoMonetario(getTfIntervaloPrecoCompraInicio());
    }//GEN-LAST:event_tfIntervaloPrecoCompraInicioKeyReleased

    private void tfIntervaloPrecoCompraFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoCompraFimKeyReleased
        control.validaCampoMonetario(getTfIntervaloPrecoCompraFim());
    }//GEN-LAST:event_tfIntervaloPrecoCompraFimKeyReleased

    private void tfQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeKeyReleased
        control.validaCampoMonetario(getTfQuantidade());
    }//GEN-LAST:event_tfQuantidadeKeyReleased

    private void tfIntervaloPrecoVendaInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoVendaInicioKeyReleased
        control.validaCampoMonetario(getTfIntervaloPrecoVendaInicio());
    }//GEN-LAST:event_tfIntervaloPrecoVendaInicioKeyReleased

    private void tfIntervaloPrecoVendaFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIntervaloPrecoVendaFimKeyReleased
        control.validaCampoMonetario(getTfIntervaloPrecoVendaFim());
    }//GEN-LAST:event_tfIntervaloPrecoVendaFimKeyReleased

    private void tfPrecoCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoCompraKeyReleased
        control.validaCampoMonetario(getTfPrecoCompra());
    }//GEN-LAST:event_tfPrecoCompraKeyReleased

    private void tfPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoVendaKeyReleased
        control.validaCampoMonetario(getTfPrecoVenda());
    }//GEN-LAST:event_tfPrecoVendaKeyReleased

    private void btAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAplicarMouseClicked
        control.aplicarFiltrosAction();
    }//GEN-LAST:event_btAplicarMouseClicked

    private void btZerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZerarMouseClicked
        control.zerarAction();
    }//GEN-LAST:event_btZerarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        control.comprarEstoqueAction();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btVendasProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendasProdutoMouseClicked
        control.verVendaProdutoAction();
    }//GEN-LAST:event_btVendasProdutoMouseClicked

    public JButton getBtAlterarProduto() {
        return btAlterarProduto;
    }

    public void setBtAlterarProduto(JButton btAlterarProduto) {
        this.btAlterarProduto = btAlterarProduto;
    }

    public JButton getBtAplicar() {
        return btAplicar;
    }

    public void setBtAplicar(JButton btAplicar) {
        this.btAplicar = btAplicar;
    }

    public JButton getBtCadastrarProduto() {
        return btCadastrarProduto;
    }

    public void setBtCadastrarProduto(JButton btCadastrarProduto) {
        this.btCadastrarProduto = btCadastrarProduto;
    }

    public JButton getBtComprasProduto() {
        return btComprasProduto;
    }

    public void setBtComprasProduto(JButton btComprasProduto) {
        this.btComprasProduto = btComprasProduto;
    }

    public JButton getBtExcluirProduto() {
        return btExcluirProduto;
    }

    public void setBtExcluirProduto(JButton btExcluirProduto) {
        this.btExcluirProduto = btExcluirProduto;
    }

    public JButton getBtVendasProduto() {
        return btVendasProduto;
    }

    public void setBtVendasProduto(JButton btVendasProduto) {
        this.btVendasProduto = btVendasProduto;
    }

    public JButton getBtZerar() {
        return btZerar;
    }

    public void setBtZerar(JButton btZerar) {
        this.btZerar = btZerar;
    }

    public JTable getTblProdutos() {
        return tblProdutos;
    }

    public void setTblProdutos(JTable tblProdutos) {
        this.tblProdutos = tblProdutos;
    }

    public JTextField getTfIntervaloPrecoCompraFim() {
        return tfIntervaloPrecoCompraFim;
    }

    public void setTfIntervaloPrecoCompraFim(JTextField tfIntervaloPrecoCompraFim) {
        this.tfIntervaloPrecoCompraFim = tfIntervaloPrecoCompraFim;
    }

    public JTextField getTfIntervaloPrecoCompraInicio() {
        return tfIntervaloPrecoCompraInicio;
    }

    public void setTfIntervaloPrecoCompraInicio(JTextField tfIntervaloPrecoCompraInicio) {
        this.tfIntervaloPrecoCompraInicio = tfIntervaloPrecoCompraInicio;
    }

    public JTextField getTfIntervaloPrecoVendaFim() {
        return tfIntervaloPrecoVendaFim;
    }

    public void setTfIntervaloPrecoVendaFim(JTextField tfIntervaloPrecoVendaFim) {
        this.tfIntervaloPrecoVendaFim = tfIntervaloPrecoVendaFim;
    }

    public JTextField getTfIntervaloPrecoVendaInicio() {
        return tfIntervaloPrecoVendaInicio;
    }

    public void setTfIntervaloPrecoVendaInicio(JTextField tfIntervaloPrecoVendaInicio) {
        this.tfIntervaloPrecoVendaInicio = tfIntervaloPrecoVendaInicio;
    }

    public JTextField getTfPrecoCompra() {
        return tfPrecoCompra;
    }

    public void setTfPrecoCompra(JTextField tfPrecoCompra) {
        this.tfPrecoCompra = tfPrecoCompra;
    }

    public JTextField getTfPrecoVenda() {
        return tfPrecoVenda;
    }

    public void setTfPrecoVenda(JTextField tfPrecoVenda) {
        this.tfPrecoVenda = tfPrecoVenda;
    }

    public JTextField getTfProduto() {
        return tfProduto;
    }

    public void setTfProduto(JTextField tfProduto) {
        this.tfProduto = tfProduto;
    }

    public JTextField getTfQuantidade() {
        return tfQuantidade;
    }

    public void setTfQuantidade(JTextField tfQuantidade) {
        this.tfQuantidade = tfQuantidade;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarProduto;
    private javax.swing.JButton btAplicar;
    private javax.swing.JButton btCadastrarProduto;
    private javax.swing.JButton btComprasProduto;
    private javax.swing.JButton btExcluirProduto;
    private javax.swing.JButton btGerarPdf;
    private javax.swing.JButton btVendasProduto;
    private javax.swing.JButton btZerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField tfIntervaloPrecoCompraFim;
    private javax.swing.JTextField tfIntervaloPrecoCompraInicio;
    private javax.swing.JTextField tfIntervaloPrecoVendaFim;
    private javax.swing.JTextField tfIntervaloPrecoVendaInicio;
    private javax.swing.JTextField tfPrecoCompra;
    private javax.swing.JTextField tfPrecoVenda;
    private javax.swing.JTextField tfProduto;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
