/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PrincipalControl;
import entities.Usuario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.ImageIcon;

/**
 *
 * @author erick.costa
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static TelaPrincipal instancia;
    PrincipalControl control;

    /**
     * Creates new form TelaPrincipal
     */
    private TelaPrincipal(Usuario usuario) {
        addWindowListener(listener);
        control = new PrincipalControl(this, usuario);
        getWindowsLookAndFeel();
        initComponents();
        control.configuracaoInicial();
    }
    
    public static synchronized TelaPrincipal getInstancia(Usuario usuario) {
        if (instancia == null) {
            instancia = new TelaPrincipal(usuario);
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuCaixa = new javax.swing.JMenu();
        menuFornecedor = new javax.swing.JMenu();
        menuEstoque = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        menuCompras = new javax.swing.JMenu();
        menuCadastroUsuario = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Mercado");
        setIconImage(new ImageIcon(System.getProperty("user.dir") + "/src/resources/teste1.2.png").getImage());

        menuCaixa.setText("Caixa");
        menuCaixa.setMinimumSize(new java.awt.Dimension(27, 50));
        menuCaixa.setPreferredSize(new java.awt.Dimension(40, 19));
        menuCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCaixaMouseClicked(evt);
            }
        });
        barraMenu.add(menuCaixa);

        menuFornecedor.setText("Fornecedores");
        menuFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFornecedorMouseClicked(evt);
            }
        });
        barraMenu.add(menuFornecedor);

        menuEstoque.setText("Estoque");
        menuEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEstoqueMouseClicked(evt);
            }
        });
        barraMenu.add(menuEstoque);

        menuCliente.setText("Clientes");
        menuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClienteMouseClicked(evt);
            }
        });
        barraMenu.add(menuCliente);

        menuVendas.setText("Vendas");
        menuVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVendasMouseClicked(evt);
            }
        });
        barraMenu.add(menuVendas);

        menuCompras.setText("Compras");
        menuCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuComprasMouseClicked(evt);
            }
        });
        barraMenu.add(menuCompras);

        menuCadastroUsuario.setText("Cadastro Usuario");
        menuCadastroUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastroUsuarioMouseClicked(evt);
            }
        });
        barraMenu.add(menuCadastroUsuario);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        barraMenu.add(menuSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFornecedorMouseClicked
        control.abrirFornecedoresAction();
    }//GEN-LAST:event_menuFornecedorMouseClicked

    private void menuCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCaixaMouseClicked
        control.abrirCaixaAction();
    }//GEN-LAST:event_menuCaixaMouseClicked

    private void menuEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEstoqueMouseClicked
        control.abrirEstoqueAction(false);
    }//GEN-LAST:event_menuEstoqueMouseClicked

    private void menuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClienteMouseClicked
        control.abrirClientesAction();
    }//GEN-LAST:event_menuClienteMouseClicked

    private void menuVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVendasMouseClicked
        control.abrirVendasAction();
    }//GEN-LAST:event_menuVendasMouseClicked

    private void menuComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuComprasMouseClicked
        control.abrirComprasAction();
    }//GEN-LAST:event_menuComprasMouseClicked

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        control.sairAction();
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuCadastroUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastroUsuarioMouseClicked
        control.abrirCadastroUsuarioAction();
    }//GEN-LAST:event_menuCadastroUsuarioMouseClicked

    WindowListener listener = new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent w) {
            instancia = null;
        }
    };
    
    public JMenu getMenuCaixa() {
        return menuCaixa;
    }

    public void setMenuCaixa(JMenu menuCaixa) {
        this.menuCaixa = menuCaixa;
    }

    public JMenu getMenuFornecedor() {
        return menuFornecedor;
    }

    public void setMenuFornecedor(JMenu menuFornecedor) {
        this.menuFornecedor = menuFornecedor;
    }

    public JMenu getMenuCliente() {
        return menuCliente;
    }

    public void setMenuCliente(JMenu menuCliente) {
        this.menuCliente = menuCliente;
    }

    public JMenu getMenuCompras() {
        return menuCompras;
    }

    public void setMenuCompras(JMenu menuCompras) {
        this.menuCompras = menuCompras;
    }

    public JMenu getMenuEstoque() {
        return menuEstoque;
    }

    public void setMenuEstoque(JMenu menuEstoque) {
        this.menuEstoque = menuEstoque;
    }

    public JMenu getMenuSair() {
        return menuSair;
    }

    public void setMenuSair(JMenu menuSair) {
        this.menuSair = menuSair;
    }

    public JMenu getMenuVendas() {
        return menuVendas;
    }

    public void setMenuVendas(JMenu menuVendas) {
        this.menuVendas = menuVendas;
    }

    public JMenuBar getBarraMenu() {
        return barraMenu;
    }

    public void setBarraMenu(JMenuBar barraMenu) {
        this.barraMenu = barraMenu;
    }
    
    public void getWindowsLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuCadastroUsuario;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuVendas;
    // End of variables declaration//GEN-END:variables
}
